name: arslan-md
routes:
  - src: /
    dest: /

services:
  - name: arslan-md-bot
    git:
      repo: https://github.com/Arslan-MD/Arslan-MD
      branch: main
    buildCommand: npm install
    runCommand: node server.js
    env:
      - key: PORT
        value: "8000"
    regions:
      - fra
    instanceType: micro
